### ISSUE TITLE
Perform power budget for flight

### ISSUE THREAD

**Issue by ivogeorg** [MSUSAT/balloonsat#18]
# Description

Budget for continuous 2.5 hours operation of the chosen payload. See image:
![image](https://user-images.githubusercontent.com/6043344/138940179-51c16770-595e-4128-8259-cc477768b6cd.png)

# Knowledge

Component | Voltage | Max current | Operating power
-- | -- | -- | --
RPI 4 | | |
EP-0136 | | |
RockBLOCK | | |
MAX-M8Q GPS receiver | | |
RPI camera v1 | | |
I2C sensor daisy chain | | |

**Comment by dperry29** [comment]
Will use battery logger to monitor charge/discharge cycle
